### ISSUE TITLE
Wii Cam?

### ISSUE THREAD

**Issue by srvoets** [Fusion-Lightguns/Fusion-Light-Gun#2]
Is there a plan to be able to use a wii camera instead of DF robot?

**Comment by Fusion-Lightguns** [comment]
In theory you can use it now . You just need to run the wires right . 
 I have a pcb from China that uses a Pro Micro and a wii . I have a sketch that works with it fine I just used different pin numbers.

I have considered getting a pcb made, it would make the wii camera go to pin heads for sda, sdl, vcc and gnd.

**Comment by Fusion-Lightguns** [comment]
I have now made a pcb that is for the wii camera . You can order yourself and assemble . 

I advice having jlcpcb or similar assemble everything but camera for you. Then solder camera. You can find them in my Lightgun PCB repo.

**Comment by Fusion-Lightguns** [comment]
So i never found a source for wii camera. 

Heres my repo for PCB that using that camera 
https://github.com/Fusion-Lightguns/Light-Gun-PCBs/tree/main/Fusion%20PCBs/Camera-PCB/Version-1.00

Im closing this issue now due to lack of cameras and intrest.
